name: Deploy webapp
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Rsync webapp
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install rsync
      - name: Install known_hosts file
        run: |
            mkdir ~/.ssh && \
            chmod 700 ~/.ssh && \
            echo ${{ secrets.SSH_KNOWN_HOSTS }} > ~/.ssh/known_hosts && \
            chmod 600 ~/.ssh/known_hosts
      - name: List files
        run: ls -alR ..
      - name: Copy webapp to host
        run: |
          ssh-agent bash -c "ssh-add <(echo '${{ secrets.SSH_PRIVATE_KEY }}') \
                          && rsync -ae 'ssh -p ${{ secrets.PORT }}' --delete --exclude='.*/' \
                          ../pqc-charts-website ${{ secrets.HOST }}:/home/nginx/pqc-charts/"
